package org.ieee11073.sdc.dpws.soap.wseventing;

/**
 * WS-Eventing configuration identifiers.
 */
public class WsEventingConfig {
    /**
     * Control maximum duration to grant for a subscription [in seconds].
     *
     * This configuration value is used by the event source to designate a maximum duration that it will permit for
     * subscriptions to last.
     *
     * - Data type: {@linkplain java.time.Duration}
     * - Use: optional
     */
    public static final String SOURCE_MAX_EXPIRES = "WsEventing.Source.MaxExpires";

    /**
     * A pre-defined subscription manager URI.
     *
     * This URI part will be used by the event source as the default subscription manager URI part. Do not muddle up
     * that value with subscription ids. Those will be generated by the event source automatically.
     *
     * - Data type: {@linkplain java.net.URI}
     * - Use: optional
     */
    public static final String SOURCE_SUBSCRIPTION_MANAGER_PATH = "WsEventing.Source.SubscriptionManagerPath";

    /**
     * Provide the retry count for notification delivery failures.
     *
     * After retry count is reached, the subscription is automatically ended.
     *
     * - Data type: {@linkplain Integer}
     * - Use: optional
     */
    public static final String SOURCE_MAX_RETRIES_ON_DELIVERY_FAILURE = "WsEventing.Source.MaxRetriesOnDeliveryFailure";

    /**
     * Duration after a notification in the outgoing notification queue of a WS Eventing notification source is stale.
     *
     * - Data type: {@linkplain java.time.Duration}
     * - Use: optional
     */
    public static final String NOTIFICATION_STALE_DURATION = "WsEventing.Source.NotificationStaleDuration";

    /**
     * Default expires value to generated on subscribe requests.
     *
     * - Data type: {@linkplain java.time.Duration}
     * - Use: optional
     */
    public static final String SINK_DEFAULT_REQUESTED_EXPIRES = "WsEventing.Sink.DefaultRequestedExpires";

    /**
     * Default period before trying to auto-renew a subscription.
     *
     * - Data type: {@linkplain java.time.Duration}
     * - Use: optional
     */
    public static final String AUTO_RENEW_BEFORE_EXPIRES = "WsEventing.Sink.AutoRenewBeforeExpires";

    /**
     * Default thread pool size for auto-renew jobs.
     *
     * - Data type: {@linkplain Integer}
     * - Use: optional
     */
    public static final String AUTO_RENEW_THREAD_POOL_SIZE = "WsEventing.Sink.AutoRenewThreadPoolSize";
}
